recipes-kernel/linux/files/t600/patches/0006-fix-the-cold-reset-function-with-the-new-SYSTEM-CPLD.patch, recipes-kernel/linux/linux-qoriq-sdk.bbappend, recipes-kernel/linux/linux-qoriq_%.bbappend
According to the new CPLD spec, we change the code to implement the cold restart function.
ACCTON-12 "HARD/WARM reset not working"
=> update accton cpld driver.

recipes-kernel/linux/files/t600/patches/0006-fix-the-cold-reset-function-with-the-new-SYSTEM-CPLD.patch, recipes-kernel/linux/files/t600/patches/0007-fix-the-order-of-fan-number-with-the-new-FAN-CPLD.patch, recipes-kernel/linux/files/t600/patches/0008-update-the-MDEC-control-method-that-provided-by-hott.patch, recipes-kernel/linux/files/t600/patches/0009-Fix-port1-always-turn-off-issue.-We-make-mistake-whe.patch, recipes-kernel/linux/files/t600/patches/0010-support-ps_shutdown.patch, recipes-kernel/linux/linux-qoriq-sdk.bbappend, recipes-kernel/linux/linux-qoriq_%.bbappend
ACCTON-75 Not implement Kernel patch for ps_shutdown
=> Support ps shutdown

recipes-kernel/linux/files/t600/patches/0006-fix-the-cold-reset-function-with-the-new-SYSTEM-CPLD.patch, recipes-kernel/linux/files/t600/patches/0007-fix-the-order-of-fan-number-with-the-new-FAN-CPLD.patch, recipes-kernel/linux/linux-qoriq-sdk.bbappend, recipes-kernel/linux/linux-qoriq_%.bbappend
fix the order of fan number issue
ACCTON-30 (some FAN CPLD functions work fail)
=> Update accton fan

recipes-kernel/linux/files/t600/patches/0006-fix-the-cold-reset-function-with-the-new-SYSTEM-CPLD.patch, recipes-kernel/linux/files/t600/patches/0007-fix-the-order-of-fan-number-with-the-new-FAN-CPLD.patch, recipes-kernel/linux/files/t600/patches/0008-update-the-MDEC-control-method-that-provided-by-hott.patch, recipes-kernel/linux/linux-qoriq-sdk.bbappend, recipes-kernel/linux/linux-qoriq_%.bbappend
There is no jira ticket and no issue.
After discuss with Hotta-san, we modified the code to the new control procedure.
=> Update accton mdec

recipes-kernel/linux/files/t600/patches/0006-fix-the-cold-reset-function-with-the-new-SYSTEM-CPLD.patch, recipes-kernel/linux/files/t600/patches/0007-fix-the-order-of-fan-number-with-the-new-FAN-CPLD.patch, recipes-kernel/linux/files/t600/patches/0008-update-the-MDEC-control-method-that-provided-by-hott.patch, recipes-kernel/linux/files/t600/patches/0009-Fix-port1-always-turn-off-issue.-We-make-mistake-whe.patch, recipes-kernel/linux/linux-qoriq-sdk.bbappend, recipes-kernel/linux/linux-qoriq_%.bbappend
ACCTON-68 QSFP Laser status is strange.
=> Fix qsfp hw pin issue

recipes-kernel/linux/files/t600/patches/0012-modify-non-linear-sk_buff-append-bytes-in-Head.patch, recipes-kernel/linux/linux-qoriq-sdk.bbappend, recipes-kernel/linux/linux-qoriq_%.bbappend
(ACCTON-116) Kernel Panic is happened when CLI execute "show interface | nomore" command from LCN
=> fix the issue that transfers the large file with SSH has problem

recipes-kernel/linux/files/t600/patches/0018-support-get-set-SFP-module-rate-autoneg-duplex-contr.patch, recipes-kernel/linux/linux-qoriq-sdk.bbappend, recipes-kernel/linux/linux-qoriq_%.bbappend
ACCTON-274 LCN SFP rate, autoneg, duplex control is required.
=> support get/set SFP(module) rate, autoneg, duplex control

recipes-dpaa/fm-ucode/fm-ucode_git.bb
meta-fss2-ppc/recipes-dpaa/fm-ucode/fm-ucode_git.bb
ACCTON-111 T600: Missing microcode image
=> add fm-ucode recipe to FOS

recipes-kernel/linux/files/t600/patches/0021-add-protection-for-multi-processes-access-the-MDEC.patch, recipes-kernel/linux/linux-qoriq_%.bbappend
ACCTON-412: /sys/bus/pci/devices/0000:03:00.0/app_locked message printed continously on DIP
=> add protection for multi processes access the MDEC.

recipes-kernel/linux/files/t600/patches/0037-Because-TCP-need-use-packet-buffer-for-retransmis.patch, recipes-kernel/linux/linux-qoriq_%.bbappend
Because TCP need use packet buffer for retransmission,
we need restore packet to original, remove add brcm tag and FCS
=> ACCTON-727 SSH session gets intermitent disconnect

recipes-kernel/linux/files/t600/patches/0039-ACCTON-727-continued-fix-dpa-tx-err-hand.patch, recipes-kernel/linux/linux-qoriq_%.bbappend
Adding one error-handling case.  Part of fix for ACCTON-727.
=> ACCTON-727-continued-fix-dpa-tx-err-handling

recipes-kernel/linux/files/t600/dts/t600.dts
1. set fix-link on the fm1mac6
2. remove the configuration on the unnecessary ports.
=> Base on FAE's suggestion,

recipes-kernel/linux/files/t600/kconfig/t600_config, recipes-kernel/linux/files/t600/patches/0042-ACCTON-858-Main-signal-is-down-after-PIU-reseat.patch, recipes-kernel/linux/linux-qoriq_%.bbappend
=> ACCTON-858: Main signal is down after PIU reseat

recipes-kernel/linux/linux-qoriq_4.1.bbappend
Add 2 missing patches to 4.1 linux bbappend
=> Add 2 missing patches to 4.1 linux bbappend

recipes-kernel/linux/files/t650/patches/0046-support-QSFPDD-EEPROM.patch, recipes-kernel/linux/linux-qoriq_4.1.bbappend
Add page 17 of port eeprom for QSFP-DD.
=> support QSFPDD EEPROM

recipes-kernel/linux/files/t600/patches/0047-Modify-sysfs-interface-from-i2c-device-to-hwmon-clas.patch, recipes-kernel/linux/linux-qoriq_4.1.bbappend
Modify the same kernel driver code as PR "update fan driver for support T650 and T600 #70"
=> sync the fan driver to t600.

recipes-kernel/linux/files/t600/patches/0051-Modify-FAN-speed-gradullay-algorithm.-Don-t-check-te.patch, recipes-kernel/linux/files/t650/patches/0051-Modify-FAN-speed-gradullay-algorithm.-Don-t-check-te.patch, recipes-kernel/linux/linux-qoriq_4.1.bbappend
Don't check temperature during gradullay change.
=> Modify FAN speed gradullay algorithm.

recipes-kernel/linux/files/t600/patches/0052-Modify-FAN-algorithm.-Don-t-check-FAN-status-in-ther.patch, recipes-kernel/linux/files/t650/patches/0052-Modify-FAN-algorithm.-Don-t-check-FAN-status-in-ther.patch, recipes-kernel/linux/linux-qoriq_4.1.bbappend
Don't check FAN status in thermal algorithm. It only check temperature.
=> Modify FAN algorithm.

recipes-kernel/linux/files/pyro/t700/dts/t700.dtsi, recipes-kernel/linux/files/t700/patches/0055-Fix-issue-ACCTON-947.patch, recipes-kernel/linux/linux-qoriq_4.1.bbappend
1. Modify mdec driver from PCI driver to platform driver.
=> Fix issue ACCTON-947.

recipes-kernel/linux/files/t700/patches/0058-Modify-blade-reset.patch, recipes-kernel/linux/files/t700/patches/0059-T700-214-Support-T700-FAN-for-kernel-driver.patch, recipes-kernel/linux/linux-qoriq_4.1.bbappend
Fix patch 0058 hard reset support, one line of accton_t600_fj_mdec.c
Fix patch 0059 T700 Fan support.  Remove lines causing patch failure in drviers/hwmon/Kconfig file.
=> fixesForPatches0058And0059

recipes-kernel/linux/files/t700/patches/0064-ACCTONCIS-82-reduce-the-i2c-access-times-during-upda.patch, recipes-kernel/linux/linux-qoriq_4.1.bbappend
Correcting additional line numbering mismatch in patch.  Updating driver version.  Updating PR.
=> Second version of fix for 0064-ACCTONCCIS-82

recipes-kernel/linux/files/t700/patches/0070-Modify-CL-power-sequence-in-mdec-driver.patch, recipes-kernel/linux/linux-qoriq_4.1.bbappend
Hotta-san request that don't power on CL port in mdec driver. DHAL should do it in provision.
=> [T700-312] dont power on CL
