FujitsuNetworkCommunications/meta-fss2-ppc

- .travis.yml
- README.md
- conf/machine/t600.conf
This will initially fail because I need a dependent commit in meta-fss-linux's fss2-init-build-env but I wanted to get the review rolling.
> Initial go at enabling Travis-CI

- .travis.yml
Running out of disk space during some runs so inherit
"rm_work" to delete more intermediate files.  Also
disable any bitbake checks for disk space so we can
go right to edge (little downside from crashing a VM or
container).
VM's get only 50 minutes and containers supposed to get 120
minutes but I'm seeing them killed after 50 minutes as well.
Our only current stable design choice is to compile subset
of recipes.  For now, that is to compile the u-boot-mkimage-native
> Settings to fit withint Travis-CI constraints

- recipes-kernel/linux/files/t600/patches/0011-decrease-Dpaa-MTU-add-BRCM-tag-and-FCS-need-use-1.patch
- recipes-kernel/linux/linux-qoriq-sdk.bbappend
- recipes-kernel/linux/linux-qoriq_%.bbappend
1. decrease Dpaa MTU, add BRCM tag and FCS need use 10 bytes
2. expand sk_buff tailroom, if it is smaller than 10 bytes
3. add Brcm tag to non-linear sk_buff
we can use tftp to transmit large file in this version, but SSH is still fail.
we will fix the SSH function in the next version.
> fix kernel panic , and packet over size drop problem

- recipes-kernel/linux/files/t600/patches/0020-remove-packet-FCS-4-bytes-come-from-BCM5389.patch
- recipes-kernel/linux/linux-qoriq_%.bbappend
ACCTON-240:upload CA and Certificate file to T600 fail via LCN00 interface.
> remove packet's 4 bytes FCS comes from BCM5389

- recipes-kernel/linux/files/t600/patches/0022-fix-2-sfp-bug.patch
- recipes-kernel/linux/linux-qoriq_%.bbappend
1. Modify sfp power bit by T600_CPLD_Spec_V08_P20181113, the old spec is reverted
2. only init QSFP ports on the PIU/MDEC device when linux probes the PCI device
> fix 2 sfp bug

- recipes-kernel/linux/files/t600/patches/0023-workaround-for-hard-reset-in-R0A-blade.patch
- recipes-kernel/linux/linux-qoriq_%.bbappend
check the blade version and then execute the reset function.
Hard reset:
R0A: execute warm reset.
R0B: execute hard reset
Accton-441: workaround the HARD reset in R0A blade
> workaround for hard-reset in R0A blade

- recipes-kernel/linux/files/t600/patches/0024-add-code-to-find-the-pci-parent-resource.patch
- recipes-kernel/linux/linux-qoriq_%.bbappend
ACCTON-313: PIU cannot bring up when PIU is inserted during power on Blade.
> add code to find the pci parent resource.

- recipes-kernel/linux/files/t600/patches/0028-ACCTON-538-Re-PM-validity-of-NW-port-EQPT-PM-is-some.patch
- recipes-kernel/linux/linux-qoriq_%.bbappend
change the mutex lock range and move the global buffer to per-piu.
1. add io_lock to protect each hardware access
2. remove original driver_lock (protect per-pci bus)
3. add mido and qsfp locks per piu, user-space app needs to use these mutex-lock to protect each operation progress.
4. move global read buffer to per piu.
> ACCTON-538: Re: PM validity of NW port EQPT PM is sometimes false

- recipes-kernel/linux/files/t600/patches/0034-ACCTON-715-IQT-6-PIU-equipmentRemoved-happened-after.patch
- recipes-kernel/linux/linux-qoriq_%.bbappend
when user inserts the PIU, DHAL tries to init the PIU (fpa_init) and fan-controller also tries to access the MDEC (mdio-access).
Maybe, it causes the kernel driver (fan controller) accesses the MDEC(MDIO) wrong.
Now, we use DHAL to update the PIU DSP temperature to fan-controller to avoid DHAL init MDEC and fan-controller access MDEC at the same time.
> ACCTON-715:(IQT#6) PIU equipmentRemoved happened after PIU replacement

- recipes-kernel/linux/files/t600/patches/0035-ACCTON-706-LED-control-does-not-work-on-FAN-slot.patch
- recipes-kernel/linux/linux-qoriq_%.bbappend
Add fanX_led_blink attribute to control LED.
> ACCTON-706: LED control does not work on FAN slot

- recipes-kernel/linux/files/t600/patches/0036-ACCTON-624-Consider-to-avoid-FPA-python-freeze-probl.patch
- recipes-kernel/linux/linux-qoriq_%.bbappend
Consider to avoid FPA python freeze problem. Sometimes DHAL is locked after user kill DHAL.
> ACCTON-624: Consider to avoid FPA python freeze problem [Future]

- recipes-kernel/linux/files/t600/patches/0040-ACCTON-727-fix_incomplete_patch-dpa-tx-err-hand-.patch
- recipes-kernel/linux/linux-qoriq_%.bbappend
Fix problem with previous patch .   Move initialization of  percpu stats above first usage.
> ACCTON-727-continued-fix-previous-err-handl-patch_

- recipes-kernel/linux/files/t600/patches/0043-ACCTON-996-Too-many-open-files-in-system.patch
- recipes-kernel/linux/linux-qoriq_3.12.bbappend
- recipes-kernel/linux/linux-qoriq_4.1.bbappend
Root Casue: After fan controller opens and reads the thermal sensor's sysfs, we do not close
it. The fan controller is a periodic task, it casues there are a lot of opened files
in the linux system.
Solution: After reading the data, we shall close the file.
> ACCTON-996: Too many open files in system

- recipes-kernel/linux/files/t600/dts/t600.dts
- recipes-kernel/linux/linux-qoriq_3.12.bb
Fix include error. linux-3.12 t600.dts had linux-4.1 file included
> Fix include error. linux-3.12 t600.dts had linux-4.1 file included

- recipes-kernel/linux/files/t600/patches/0044-Fan-speed-changes-to-max-automatically.patch
- recipes-kernel/linux/linux-qoriq_4.1.bbappend
Root casue:
FAN driver uses Linux string conversion API to get temperature string. When this
API return error, the temperature value is wrong, it casues FAN driver sets
FAN to full speed.
Solution:
1. Buffer clear before read temperature, otherwise it will keep last value and cause kstrtoint parser error.
2. separate the check flag, valid and temp-is-valid, for FAN updater and temperature updater.
> [ACCTON-1013] Sometimes FAN speed change to MAX

- recipes-kernel/linux/files/pyro/t650/dts/t650.dtsi
- recipes-kernel/linux/files/t650/patches/0047-Modify-sysfs-interface-from-i2c-device-to-hwmon-clas.patch
- recipes-kernel/linux/linux-qoriq_4.1.bbappend
Hardware design has a little bit difference between T600 and T650,
1. we change the DTS to support new FAN eeprom
2. we change the path of sysfs from bus/i2c/ to class/ in the fan driver, it is common and hardware independence.
> update fan driver for support T650 and T600

- recipes-kernel/linux/files/t600/patches/0040-4.1-ACCTON-727-fix_incomplete_patch-dpa-tx-err-hand.patch
- recipes-kernel/linux/linux-qoriq_4.1.bbappend
This change was made by James Dang in our bitbucket, but the version on Github has never been updated.  I am not sure how the 4.1 kernel has been building previously, because it failed for me without this change after yesterday's delivery.
> deliver_missed_correction_to_patch_0040-4.1

- recipes-kernel/linux/files/t600/patches/0054-Send-ATA_CMD_IDLEIMMEDIATE-command-to-sda-when-syste.patch
- recipes-kernel/linux/files/t650/patches/0054-Send-ATA_CMD_IDLEIMMEDIATE-command-to-sda-when-syste.patch
There was an error with the patch where it attempted to fix an unnecessary space at the start of the definition of function show_bootstatus().
> Fix_minor_issue_with_patch_0054

- recipes-kernel/linux/files/pyro/t700/dts/t700.dtsi
- recipes-kernel/linux/files/t700/patches/0060-Fix-hardware-reset-and-blade-eeprom-issues.patch
- recipes-kernel/linux/linux-qoriq_4.1.bbappend
1. T700-230: Blade EEPROM is null in bank2
Modify blade driver to 24c64. It support 16 bit address mapping.
24c04 - 512 byte, address pointer is 8 bit
24c64 - 8192 byte, address pointer is 16 bit
2. T700-203: Provide Kernel patch for blade hardware reset
Fix bug and supportT 700 power off function.
>  Fix hardware reset and blade eeprom issues

- recipes-kernel/linux/files/t700/patches/0060-Fix-hardware-reset-and-blade-eeprom-issues.patch
Change patch 0060 to leave the mapping of linux reset types unchanged.
> reverse_reset_remap_of_0060

- recipes-kernel/linux/files/t700/patches/0061-T700-232-leap-year-issue.patch
- recipes-kernel/linux/linux-qoriq_4.1.bbappend
Modify RTC to 2000 year base. The default time is 2000/1/1 0:0:0.
> [T700-232] leap year issue.

- recipes-kernel/linux/files/t700/patches/0063-Modify-FAN_REG_CONT-index.patch
- recipes-kernel/linux/linux-qoriq_4.1.bbappend
The index value should be 20. It is mapping register 0x46.
> ACCTONCIS-120: fix wrong fan_reg_count index

- recipes-kernel/linux/files/t700/patches/0064-ACCTONCIS-82-reduce-the-i2c-access-times-during-upda.patch
- recipes-kernel/linux/linux-qoriq_4.1.bbappend
Add i2c smbus xfer for every CL port.
1. Application can read QSFP PI by i2cget command.
2. There are 12 mutex for every CL port.
> ACCTONCIS-82: reduce the i2c access times during updating the QSFP's PM

- recipes-kernel/linux/files/t700/patches/0064-ACCTONCIS-82-reduce-the-i2c-access-times-during-upda.patch
Fixed patching error by removing spurious blank line addition near 
-1208,12 +1268,18.
Also removed all tabs from code additions and replaced with spaces.
> fix for misalignment in patch 0064 ACCTONCIS-82

- recipes-kernel/linux/files/t700/patches/0068-Fix-ACCTONCIS-172-Kernel-mutex.patch
- recipes-kernel/linux/linux-qoriq_4.1.bbappend
1. Use mutex_lock_interruptible instead of mutex_lock
2. Fellow "QSFP_Driver_Specification_v0.6.1" to modify QSFP driver.
> Fix ACCTONCIS-172 Kernel mutex.
